import './style.css';

const links = { github:'https://github.com/Tanito', linkedin:'https://www.linkedin.com/in/ulises-delia/', email:'mailto:ulises.d83@gmail.com', cotizar:'https://play.google.com/store/apps/details?id=com.evolvere.CotizAR' };
const skills = [['TS','TypeScript','blue'],['N','Node.js','green'],['N','NestJS','red'],['R','React','cyan'],['RN','React Native','violet'],['DB','MongoDB','emerald'],['PG','PostgreSQL','navy'],['GQL','GraphQL','pink'],['API','REST APIs','orange'],['AWS','AWS','sky'],['DO','Docker','coral'],['⌘','Git','dark']];
const projects = [
  {num:'01',name:'CotizAR',type:'Aplicación móvil · Publicada',desc:'Producto móvil propio publicado oficialmente en Google Play. Una experiencia real de desarrollo end-to-end, desde la construcción hasta la distribución.',tags:['React Native','Mobile','Google Play'],featured:true,url:links.cotizar, action:'Abrir en Google Play'},
  {
    num: '02',
    name: 'Permutar',
    type: 'Marketplace · Backend',
    desc: 'Backend de marketplace de compra, venta y permuta. Desarrollé la API, autenticación y roles, publicaciones con campos dinámicos, búsqueda, integración de pagos y persistencia de datos.',
    tags: ['NestJS', 'PostgreSQL', 'Prisma', 'REST API'],
    featured: true,
    url: 'https://permutar.com.ar',
    action: 'Ver proyecto'
  },
  {
  num: '03',
  name: 'Rumbo Fit',
  type: 'App móvil · En desarrollo',
  desc: 'Aplicación fitness para registrar comidas, entrenamientos, medidas corporales y progreso personal. Actualmente en desarrollo, con enfoque local-first.',
  tags: ['React Native', 'Expo', 'Firebase', 'TypeScript'],
  url: 'https://github.com/Tanito/rumbofit',
  action: 'Ver repositorio'
}
];
const skillHTML = skills.map(([icon,name,color])=>`<div class="skill"><span class="skill-icon ${color}">${icon}</span><span>${name}</span></div>`).join('');
const projectHTML = projects.map(p=>`<article class="project ${p.featured?'featured':''}"><div class="project-art"><span class="project-number">${p.num}</span>${p.featured?'<span class="published">PUBLICADO</span>':''}<div class="art-lines"></div><span class="art-label">${p.featured?'COTIZAR / MOBILE':'BUILD / SHIP / LEARN'}</span></div><div class="project-copy"><p class="eyebrow">${p.type}</p><h3>${p.name}</h3><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><a class="text-link" href="${p.url}" target="_blank" rel="noopener">${p.action} ↗</a></div></article>`).join('');

document.querySelector('#app').innerHTML = `<header class="topbar"><a class="brand" href="#inicio"><span>U<span>.</span></span><b>Ulises D'Elia</b></a><nav><a href="#sobre-mi">Sobre mí</a><a href="#stack">Stack</a><a href="#experiencia">Experiencia</a><a href="#proyectos">Proyectos</a><a href="#educacion">Formación</a></nav><div class="nav-tools"><button class="lang active" data-lang="en">EN</button><span>/</span><button class="lang" data-lang="es">ES</button><a class="nav-cta" href="${links.email}">Hablemos ↗</a></div></header><main>
<section id="inicio" class="hero"><div class="hero-copy"><p class="kicker"><i></i> Disponible para nuevos desafíos</p><h1>Construyo productos<br><em>que llegan lejos.</em></h1><p class="lede">Full Stack Developer con foco en backend y arquitectura. Diseño y desarrollo aplicaciones completas, desde la idea hasta producción.</p><div class="actions"><a class="button primary" href="#proyectos">Ver proyectos ↓</a><a class="button secondary" id="cv-download" href="/cv-ulises-delia-en.pdf" download>Descargar CV ↓</a></div><div class="socials"><a href="${links.github}" target="_blank">GitHub ↗</a><a href="${links.linkedin}" target="_blank">LinkedIn ↗</a><a href="${links.email}">Email ↗</a></div></div><div class="hero-visual"><div class="visual-grid"></div><div class="code-card top"><span>01</span><code>const <b>product</b> =</code><code>buildForImpact();</code></div><div class="portrait"><img src="/portrait.png" alt="Retrato de Ulises D'Elia"/></div><div class="visual-meta"><span>FULL STACK</span><span>LA PLATA · BUENOS AIRES · ARG</span></div><div class="code-card bottom"><span>API</span><b>+</b><span>DATA</span><b>+</b><span>UX</span></div></div></section>
<section id="sobre-mi" class="split section"><div class="label"><small>01</small> Sobre mí</div><div class="content"><h2>Ingeniería con<br><em>visión de producto.</em></h2><p class="lead">Me especializo en crear software robusto, mantenible y preparado para crecer.</p><p>Trabajo principalmente con TypeScript, Node.js/NestJS, React, React Native y bases de datos relacionales y no relacionales. Me involucro en la definición técnica, el diseño de arquitectura, las integraciones y el despliegue, buscando resolver problemas reales de negocio con claridad y criterio.</p><div class="facts"><div><strong>End-to-end</strong><span>del diseño al deploy</span></div><div><strong>Backend first</strong><span>arquitectura y lógica</span></div><div><strong>Producción</strong><span>software que funciona</span></div></div></div></section>
<section id="stack" class="stack section"><div class="section-head"><div class="label"><small>02</small> Stack</div><h2>Herramientas para<br><em>hacerlo realidad.</em></h2><p>Una base técnica versátil para construir productos consistentes, escalables y fáciles de mantener.</p></div><div class="skills-grid">${skillHTML}</div></section>
<section id="experiencia" class="split section experience"><div class="label"><small>03</small> Experiencia</div><div class="content"><h2>Experiencia que<br><em>se nota en el código.</em></h2><article class="job featured-job"><div><span>2021 — Presente</span><span>Chile · Remoto</span></div><div><h3>Outliers Capital</h3><b>Full Stack Developer</b><p>Desarrollo de productos completos, con especial foco en backend, arquitectura, APIs e integración de servicios. Trabajo con JavaScript, TypeScript, React, MongoDB, NestJS y GraphQL.</p></div></article><article class="job"><div><span>2021</span><span>Colombia · Remoto</span></div><div><h3>Mi Águila</h3><b>Backend Developer</b><p>Desarrollo backend y mantenimiento de servicios con JavaScript, MongoDB y Sequelize.</p></div></article><article class="job muted"><div><span>2010 — 2019</span><span>Argentina</span></div><div><h3>Ministerio de Desarrollo y Acción Social</h3><b>Recursos humanos</b></div></article></div></section>
<section id="proyectos" class="projects section"><div class="section-head"><div class="label"><small>04</small> Proyectos</div><h2>De la idea a algo<br><em>que la gente puede usar.</em></h2><p>Una selección de proyectos personales y productos publicados.</p></div><div class="projects-grid">${projectHTML}</div></section>
<section id="educacion" class="split section education"><div class="label"><small>05</small> Formación</div><div class="content"><h2>Siempre<br><em>aprendiendo.</em></h2><div class="edu"><div><span>2026</span><strong>Analista Universitario en Gestión de Riesgos Cibernéticos</strong><small>Universidad de la Defensa Nacional · UNDEF</small></div><div><span>2020 — 2021</span><strong>Full Stack Developer</strong><small>Henry</small></div></div><div class="languages"><span>Español · Nativo</span><span>Italiano · Bilingüe</span><span>Inglés · Bueno</span></div></div></section>
<section id="contacto" class="contact"><p class="kicker">¿Tenés un desafío?</p><h2>Hagamos algo<br><em>que importe.</em></h2><a class="button primary" href="${links.email}">Escribime ↗</a><div class="contact-links"><a href="${links.github}" target="_blank">GitHub ↗</a><a href="${links.linkedin}" target="_blank">LinkedIn ↗</a><a href="${links.email}">ulises.d83@gmail.com ↗</a></div></section></main><footer><span>© 2026 Ulises D'Elia</span><span>Full Stack Developer · Buenos Aires, AR</span><a href="#inicio">Volver arriba ↑</a></footer>`;

const en = {'Sobre mí':'About me','Experiencia':'Experience','Proyectos':'Projects','Formación':'Education','Hablemos ↗':'Let’s talk ↗','Disponible para nuevos desafíos':'Available for new challenges','Construyo productos':'I build products','que llegan lejos.':'that go far.','Full Stack Developer con foco en backend y arquitectura. Diseño y desarrollo aplicaciones completas, desde la idea hasta producción.':'Full Stack Developer focused on backend and architecture. I design and build complete applications, from idea to production.','Trabajo principalmente con TypeScript, Node.js/NestJS, React, React Native y bases de datos relacionales y no relacionales. Me involucro en la definición técnica, el diseño de arquitectura, las integraciones y el despliegue, buscando resolver problemas reales de negocio con claridad y criterio.':'I mainly work with TypeScript, Node.js/NestJS, React, React Native, and relational and non-relational databases. I get involved in technical definition, architecture, integrations, and deployment, aiming to solve real business problems with clarity and good judgment.','Ver proyectos ↓':'View projects ↓','Descargar CV ↓':'Download CV ↓','Ingeniería con':'Engineering with','visión de producto.':'a product mindset.','Me especializo en crear software robusto, mantenible y preparado para crecer.':'I specialize in building robust, maintainable software ready to scale.','End-to-end':'End-to-end','del diseño al deploy':'from design to deployment','Backend first':'Backend first','arquitectura y lógica':'architecture and logic','Producción':'Production','software que funciona':'software that works','Herramientas para':'Tools to','hacerlo realidad.':'make it real.','Una base técnica versátil para construir productos consistentes, escalables y fáciles de mantener.':'A versatile technical foundation for building consistent, scalable, and maintainable products.','Experiencia que':'Experience you can','se nota en el código.':'see in the code.','De la idea a algo':'From an idea to something','que la gente puede usar.':'people can use.','Siempre':'Always','aprendiendo.':'learning.','¿Tenés un desafío?':'Have a challenge?','Hagamos algo':'Let’s make something','que importe.':'that matters.','Escribime ↗':'Write to me ↗','Volver arriba ↑':'Back to top ↑','PUBLICADO':'PUBLISHED','Abrir en Google Play':'Open on Google Play','Aplicación móvil · Publicada':'Mobile app · Published','API · Proyecto personal':'API · Personal project','App · Web + Android':'App · Web + Android','E-commerce · Proyecto personal':'E-commerce · Personal project','Recursos humanos':'Human Resources'};
Object.assign(en, {'Desarrollo de productos completos, con especial foco en backend, arquitectura, APIs e integración de servicios. Trabajo con JavaScript, TypeScript, React, MongoDB, NestJS y GraphQL.':'Building complete products with a strong focus on backend, architecture, APIs, and service integrations. Working with JavaScript, TypeScript, React, MongoDB, NestJS, and GraphQL.','Desarrollo backend y mantenimiento de servicios con JavaScript, MongoDB y Sequelize.':'Backend development and service maintenance with JavaScript, MongoDB, and Sequelize.','2021 — Presente':'2021 — Present','Chile · Remoto':'Chile · Remote','2010 — 2019':'2010 — 2019','Argentina':'Argentina'});
const original = new WeakMap();
function language(lang){document.documentElement.lang=lang;document.querySelectorAll('body *').forEach(el=>el.childNodes.forEach(n=>{if(n.nodeType!==3||!n.textContent.trim())return;if(!original.has(n))original.set(n,n.textContent);const value=original.get(n);n.textContent=lang==='en'?(en[value.trim()]||value):value}));document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.querySelector('#cv-download').href=lang==='en'?'/cv-ulises-delia-en.pdf':'/cv-ulises-delia-es.pdf'}
document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>language(b.dataset.lang)));
language('en');
